services:
  backend-migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      # O Prisma encontrará o DB em /app/prisma/dev.db
      - DATABASE_URL=file:./prisma/dev.db
    volumes:
      # Mapeia todo o backend. Isso inclui o schema e o local onde o DB será criado.
      - ./backend:/app
    command: npx prisma migrate deploy
    container_name: dashboard-backend-migrate

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "3001:3001"
    volumes:
      # Em produção, o banco de dados é o único volume que precisamos persistir.
      # O código da aplicação já está na imagem.
      - ./backend/prisma:/app/prisma
    environment:
      - DATABASE_URL=file:./prisma/dev.db
    container_name: dashboard-backend
    depends_on:
      backend-migrate:
        condition: service_completed_successfully

  frontend:
    build:
      context: ./meu-dashboard-pro
      dockerfile: Dockerfile.prod
    ports:
      # Mapeia a porta 5173 da sua máquina para a porta 80 do contêiner Nginx.
      - "5173:80"
    container_name: dashboard-frontend
    depends_on:
      - backend

# Define a rede para que os contêineres possam se comunicar.
networks:
  default:
    driver: bridge 