services:
  backend-migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile # Usa o Dockerfile de dev
    volumes:
      # Garante que o migrate use o código local
      - ./backend:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Usa o Dockerfile de dev
    command: npm run dev # Sobrescreve o CMD do Dockerfile.prod
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./meu-dashboard-pro
      dockerfile: Dockerfile # Usa o Dockerfile de dev
    command: npm run dev -- --host # Garante que o vite rode corretamente
    ports:
      - "5174:5173" # Usa a porta do vite, mas mapeia para 5174 na sua máquina
    volumes:
      - ./meu-dashboard-pro:/app
      - /app/node_modules 